Feature/multi bidding
assume-framework/assume pull request #109
Opened 2023-07-21 10:44 UTC by maurerle

first steps to multi bidding of various products in one market opening

2023-07-21 11:12 UTC, nick-harder commented on assume/common/utils.py
> +    orderbook.sort(key=itemgetter("node_id"))
I find always better to have x = x+1 formulations rather then inplace formulations. Somehow its easier to read those and understand. is there a particular reason for such formulation?

2023-07-21 11:17 UTC, nick-harder commented on assume/units/powerplant.py
I find it a bad idea to have such a huge function for operational windows like this with several if else conditions. Makes reading the code way to hard, and also trying to maintain or change it. I would use the previous form

2023-07-21 11:18 UTC, nick-harder requested changes
Please review the several comments, especially the one in calculate operation windows functions.

2023-07-31 13:55 UTC, adamsjohanna approved these changes

2023-07-31 14:15 UTC, merged