Building heatpump dr integration
assume-framework/assume pull request #179
Opened 2023-09-12 11:24 UTC by nick-harder

this branch introduces the functionality of DSM units and their operation

2023-09-12 11:44 UTC, maurerle requested changes
I did not yet revise the new files, but looked at the changes to the existing framework

2023-09-12 11:44 UTC, maurerle commented on assume/optitest.py
this should be moved to the test directory and converted to a pytest test

2023-09-12 11:44 UTC, maurerle commented on assume/common/outputs.py
Thats good :)

2023-09-12 11:44 UTC, maurerle commented on assume/common/base.py
remove Union here
maybe have technology always as a list[str]?

2023-09-12 11:44 UTC, maurerle commented on assume/common/forecasts.py
>      def get_registered_market_participants(self, market_id):
this whole section seems redundant.. Doesnt the same happen if i run self["price_EOM"] for example? Why do I need the getter for this?

2023-09-12 11:44 UTC, maurerle commented on assume/world.py
> +        ------sssssssssssssssssssssssssssssssssssssssssss
remove

2023-09-12 11:44 UTC, maurerle commented on assume/world.py
> +                unit_params=unit_params if unit_params is not None else {},
This should not be necessary, by having a better default for unit_params

2023-09-12 16:41 UTC, maurerle commented on assume/units/dst_components.py
> +class Storage:
This should not be called Storage, as we already have a Storage class

2023-11-06 11:32 UTC, nick-harder commented
stale. Reopen when active and updated

2023-11-06 11:32 UTC, closed without merging