Tutorial 02
assume-framework/assume pull request #259
Opened 2023-12-07 15:45 UTC by nick-harder

This commit adds the new example. 
It also edits multiple docstring transitioning to the google style docstings. The whole common folder has been edited.
Tests have been also slightly modified, purely cosmetical changes where all marketconfigs have now parameter_name=parameter for easier reading.

2023-12-13 09:01 UTC, kim-mskw requested changes
Love the tutorials, only have minor remarks/questions :)

2023-12-13 09:01 UTC, kim-mskw commented on assume/common/market_objects.py
> +    count: int
Was that liek a concise choice of having less comennts, or was this just with regard to these comments?

2023-12-13 09:16 UTC, nick-harder commented on assume/common/scenario_loader.py
> +    Notes:
yes, the idea is to have a description but extra contents go here

2023-12-20 13:23 UTC, maurerle commented on assume/world.py
> +        manager_address: Optional[Any] = None,
Where is this still missing?

2023-12-20 13:23 UTC, maurerle commented on examples/notebooks/04_Reinforcement_learning_example.ipynb
> +    "# 4. Reinforcement learning example\n",
solved

2023-12-20 13:25 UTC, maurerle approved these changes
Looks good

2023-12-20 13:25 UTC, maurerle commented on assume/common/market_objects.py
> +    count: int
The comments are added to the docs above, so its fine

2023-12-20 14:13 UTC, maurerle commented
It does not look good at all.
The new doc style is so broken.

https://assume.readthedocs.io/en/latest/assume.common.html#assume.common.forecasts.CsvForecaster.calculate_residual_demand_forecast

2023-12-20 14:32 UTC, maurerle commented
This is how it should look like:
![image](https://github.com/assume-framework/assume/assets/25026204/26051ead-98b8-48b9-be34-497283567417)

This is how the GPT-docs style shows up:
![image](https://github.com/assume-framework/assume/assets/25026204/3b7b8a00-0706-425c-9be4-80343e47f24d)

We can merge this as usual and fix it afterwards.
I don't think that there is an automated way to parse the GPT docs suggestions and fix them.

2023-12-20 18:11 UTC, kim-mskw commented on assume/common/scenario_loader.py
> +    Notes:
Yeah I was just wondering about the label "notes". But then we do it this way.

2023-12-20 18:11 UTC, kim-mskw commented on assume/common/scenario_loader.py
> +    Notes:
I documented that as well

2023-12-20 18:13 UTC, kim-mskw commented on assume/world.py
> +        manager_address: Optional[Any] = None,
Done ;)

2023-12-20 18:33 UTC, kim-mskw approved these changes

2023-12-20 18:34 UTC, merged