Documaentation of Unit example
assume-framework/assume pull request #262
Opened 2023-12-21 14:38 UTC by Manish-Khanra

Documentation of an electrlyser unit example

2023-12-21 15:50 UTC, maurerle reviewed
Adding the tutorial to the list is needed for it to show up on the docs too:
https://github.com/assume-framework/assume/blob/b3aa9c185e88061cbdfc87c38b3eaaac06b70fbf/docs/source/examples_basic.rst

2023-12-21 15:50 UTC, maurerle commented on docs/source/ASSUME_Architecture.png
There is already https://github.com/assume-framework/assume/blob/main/docs/source/img/architecture.svg
If added - this picture would belong into the same folder, but I would just use the .svg where you need it.

2023-12-21 15:50 UTC, maurerle commented on examples/notebooks/02_custom_unit_example.ipynb
> +    "![Model Architecture](ASSUME\\docs\\source\\ASSUME_Architecture.png)"
use svg here..?

2024-01-15 12:28 UTC, nick-harder commented
@kim-mskw could you please check this commit please? You have a good eye for details and consistency :-)

2024-01-15 13:00 UTC, nick-harder commented
@Manish-Khanra the part of adding the new unit type is missing. Also, you need something like %%add_to RLStrategy from tutorial 4 RL to be able to have functions inside classes up and running. Please add it where needed. Also, at the beginning, the part about docker and limitations is repeated twice. Please check

2024-01-23 12:29 UTC, maurerle commented on docs/source/examples_basic.rst
This does not look right - it should not undo the renaming

2024-01-23 13:09 UTC, nick-harder approved these changes

2024-01-23 13:17 UTC, maurerle requested changes
The tutorial in #266  is supposed to be number 5 - the market comparison tutorial is supposed to stay number 6 - I think.

2024-01-23 13:42 UTC, nick-harder commented
> The tutorial in #266 is supposed to be number 5 - the market comparison tutorial is supposed to stay number 6 - I think.

@maurerle it was decided to merge unit and strategy, so it is 3, RL is 4 and market is 5

2024-01-23 14:12 UTC, maurerle approved these changes
the electrolyzer png works on the docs but is broken on the notebook itself..
This is due to the paths being different.

We could fix this, by loading the picture with python and displaying it - resulting in the images being embedded as an output of a cell.
We could also fix this by adding a new folder /img next to the notebook, which includes this image a second time.
Both is really stupid.

We could have something like:

```python
from IPython.display import Image, display
display(Image('docs/source/img/Electrolyzer.png'))
```

2024-01-23 15:37 UTC, nick-harder commented
yes true, I changed the way how it is displayed, is ugly, but this is the only way how it works for docs, but also in collab and locally

2024-01-23 15:38 UTC, maurerle approved these changes

2024-01-23 15:41 UTC, merged