Restructure setting obs and act observations and return unique observations
assume-framework/assume pull request #351
Opened 2024-05-13 11:19 UTC by nick-harder

-set obs_dim and act_dim as properties of bidding startegies
-remove these values from configs
-set them as fixed values in startegies
-learning role checks if all strategies have the same dimensions -raise an error if not the same dimensions
-include unique observations in the critic

2024-05-13 12:46 UTC, kim-mskw requested changes

2024-05-13 12:46 UTC, kim-mskw commented on assume/reinforcement_learning/algorithms/matd3.py
> +                )
This only works if unique unitobs are at end. Is that documented somewhere?

2024-05-13 14:19 UTC, nick-harder commented on assume/reinforcement_learning/algorithms/matd3.py
> +                temp = th.cat(
yes, good point! I will look into it in a b it more details tomorrow and comment it properly

2024-05-14 13:02 UTC, kim-mskw approved these changes

2024-05-14 13:02 UTC, merged