Curation of pyproject toml and dependencies
assume-framework/assume pull request #443
Opened 2024-10-09 08:39 UTC by maurerle

* Update reuse format
* improve pypi urls in pyproject.toml for better project description
* update dependency versions, as pyomo is now compatible with numpy 2
* remove unused dependencies yaml-include and glpk

2024-10-09 10:22 UTC, nick-harder commented
@maurerle what solver would be used by default instead of glpk? Maybe we do as pypsa and use the new and nice hyggs?

2024-10-09 14:13 UTC, maurerle commented
we are using glpk as default, but we do not need the pyglpk bindings for that, as pyomo has its own interface to glpk :)

2024-10-16 08:37 UTC, nick-harder commented
> we are using glpk as default, but we do not need the pyglpk bindings for that, as pyomo has its own interface to glpk :)

yes, I understand that, pyomo has the interface, but we need some solver so people can run optimization parts of ASSUME. I believe simply installing pyomo doesn't install any solver with it, or am I wrong?

2024-10-16 09:13 UTC, maurerle commented
pyomo does bring the solver interface and detects which driver is installed.

Typically you are only `apt install glpk-utils` or `apt install coinor-cbc` away from installing a solver which works with pyomo/assume (or `brew install glpk`/`brew install cbc` on mac).

Or on windows:
* https://winglpk.sourceforge.net/
* download and extract binaries from https://github.com/coin-or/Cbc/releases
* and the Gurobi install (login required): https://www.gurobi.com/downloads/gurobi-software/

We could give hints to that in the Install docs, but this is highly system specific.

2024-10-21 12:06 UTC, nick-harder requested changes

2024-10-21 12:06 UTC, nick-harder commented on pyproject.toml
>  optimization = [
at this point we might as well rename the optimization to network since it only installs pypsa extra, what do you think?

2024-10-21 12:06 UTC, nick-harder commented on assume/markets/clearing_algorithms/complex_clearing_dmas.py
> +SOLVERS = ["appsi_highs", "glpk", "cbc", "gurobi", "cplex"]
maybe we should stick to the same order of solvers for now among files before we have a global variable for that?

2024-10-21 12:06 UTC, nick-harder commented on assume/strategies/dmas_powerplant.py
> +def get_solver_factory(solvers_str=["appsi_highs", "glpk", "cbc", "gurobi", "cplex"]):
also here, maybe use [highs, gurobi, glpk, the rest]

2024-10-22 09:27 UTC, nick-harder commented
@maurerle I have now switched to HIGHS by default and removed GLPK completely including git workflows. To supress the outputs from HIGHS I included solver options, but I still had to include getlogger to warning level for pyomo. I still have one problem though, namely constant one line prints from HIGHS when used with pypsa for example in small_redispatch example. I couldn't figure out how to solve that. Any suggestions?

2024-10-22 11:56 UTC, nick-harder commented
@maurerle I managed to remove the annoying logging from highs when used with pypsa. Could you please take a general look at the code and merge it if it is fine with you?

2024-10-22 11:58 UTC, nick-harder approved these changes

2024-10-22 21:32 UTC, merged