Explicit demand response peak load
assume-framework/assume pull request #484
Opened 2024-11-16 23:03 UTC by Manish-Khanra

# Pull Request

## Related Issue
Closes #[issue number] (if applicable)

## Description
[Provide a brief description of the changes in this PR]

## Changes Proposed
- [List the main changes or features implemented]
-
-

## Testing
[Describe the testing you've done, including any specific test cases or scenarios]

## Checklist
Please check all applicable items:

- [ ] Code changes are sufficiently documented (docstrings, inline comments, `doc` folder updates)
- [ ] New unit tests added for new features or bug fixes
- [ ] Existing tests pass with the changes
- [ ] Reinforcement learning examples are operational (for DRL-related changes)
- [ ] Code tested with both local and Docker databases
- [ ] Code follows project style guidelines and best practices
- [ ] Changes are backwards compatible, or deprecation notices added
- [ ] New dependencies added to `pyproject.toml`
- [ ] A note for the release notes `doc/release_notes.rst` of the upcoming release is included
- [ ] Consent to release this PR's code under the GNU Affero General Public License v3.0

## Additional Notes (if applicable)
[Any additional information, concerns, or areas you want reviewers to focus on]

## Screenshots (if applicable)
[Add screenshots to demonstrate visual changes]

2024-11-21 14:17 UTC, kim-mskw commented
Discussion with @Manish-Khanra we used a big-M formulation to linearise the problem formulation. The second abjective loop was reformulated to include the absolute values of the shift; otherwise, the objective value was forced to 0 due to the demand covering constraint. 

Note that there are no costs in the second objective, leading to multiple possible solutions with the same absolute load shift that does not violate the cost increase constraints. Hence, different solvers will most likely result in different solutions. 

![image](https://github.com/user-attachments/assets/11ea73ca-38dd-4676-be8a-ed1d9d4997d4)

2024-11-26 13:22 UTC, Manish-Khanra commented on assume/units/steel_plant.py
@maurerle In line 605 could you please check how to fix this error? I am getting this after merging the latest from the main. Just test by running the example 'experiment'. Thank you! :)

2024-12-03 15:00 UTC, nick-harder requested changes
@Manish-Khanra I have fixed several things and streamlined the code. Everything is fine, but there are some things you should address before we can merge this into main

2024-12-03 15:00 UTC, nick-harder commented on examples/examples.py
> +    "experiment": {"scenario": "experiment", "study_case": "dst_flexibility_case"},
experiment is not the best name for the example. maybe use the example_01 form or add the data to one of the existing examples? for example from your tutorial? I believe we don't need this extra folder

2025-01-15 15:00 UTC, nick-harder approved these changes

2025-01-15 15:02 UTC, merged